spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.221.131/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell