spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.221.131/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxb371971d30dc8b95
  mpAppSecret: c25e8ce1e66a930680fdfb2ad6c11d01